name: Build And Install GTest
description:  Build and Install GTest
inputs:
  ref:
    description: Ref/tag to use
    required: false
    default: v1.14.0
  build-dir:
    description: Checkout and Build Directory
    required: false
    default: googletest
  cmake-build-type:
    description: CMake Build Type (e.g. Debug Release)
    required: false
    default: Release
    
    
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: google/googletest.git
        path: ${{ inputs.build-dir }}
        ref: ${{ inputs.ref }}
    - name: build
      working-directory: ${{ inputs.build-dir }}
      shell: bash
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=${{inputs.cmake-build-type}} ..
        make -j
        sudo make install
