
name: build and test
on: push
jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: build and install gtest
        uses: ./.github/actions/install-gtest
      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make -j
      - name: Test
        run: |
          cd build/unittests
          ./systemf_unittests
      - name: install valgrind
        run: sudo apt update && sudo apt install -y valgrind
      - name: Run with Valgrind
        run: |
          cd build/unittests
          valgrind ./systemf_unittests
  MacOSX:
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: build and install gtest
        uses: ./.github/actions/install-gtest
      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make -j
      - name: Test
        run: |
          cd build/unittests
          ./systemf_unittests

